### ISSUE TITLE
Imprimir canvas ao invés de gerar PDF

### ISSUE THREAD

**Issue by fsobral** [MMagueta/ClassPack#5]
Dado que o PDF do Fortran está com problemas e o do Python é um desenho ruim, surgiu a sugestão de enviar para a impressora. Minha sugestão é usar o [printJS](https://printjs.crabbly.com/):

    https://printjs-4de6.kxcdn.com/print.min.js
    https://printjs-4de6.kxcdn.com/print.min.css

**Comment by MMagueta** [comment]
A função "convert_tex_document" de "latex_converter.py" está fazendo o processo do servidor entrar em modo suspenso. Ao gerar a imagem com o printJS esse problema se resolve apenas removendo a função mencionada e sua respectiva biblioteca.
